baseurl: 'https://example.org/'
languageCode: en-us
title: Terra Incognita
theme: sam
pygmentsStyle: monokai
pygmentsCodefences: true
params:
  dateform: 'Mon Jan 02, 2006'
  dateformfull: 'Mon Jan 2 2006 15:04:05 EST'
  favicon: /sam.ico
  homepage: main
  galleryFolder: images/
  clickablePhotos: true
  footerText: Terra Incognita by Alejandro Quesada
  description: By Alejandro Quesada
  twitterCard: summary_large_image
  primaryImage: /tn.png
  mainMenu:
    - link: /about
      text: about terra incognita
    - link: /posts
      text: techincal writing by quesada
