baseURL: "http://www.alexq.me"
title: "Terra Incognita"
theme: "heather-hugo"
languageCode: "en-us"

permalinks:
  post: /:year/:month/:title/

taxonomies:
  tags: ["meta", "theme", "blog"]

params:
  description: "Unknown territories"
  author:
    name: "Alejandro Quesada"
    email: "quesadaaba@gmail.com"
  readMoreLabel: "Read more"

